name: Close Preview
on:
  pull_request:
    types:
      - closed
jobs:
  close:
    name: Close
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Preview Clean
        run: echo "Trigger another workflow with full access to secrets"
